// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNoVAQ6l2TWGt4VQuE2sE8Ynk4KbdUKBM',
    appId: '1:767226093877:web:0464ec8c99644ac8cb6c7c',
    messagingSenderId: '767226093877',
    projectId: 'stunio-clone',
    authDomain: 'stunio-clone.firebaseapp.com',
    databaseURL: 'https://stunio-clone-default-rtdb.firebaseio.com',
    storageBucket: 'stunio-clone.appspot.com',
    measurementId: 'G-GJHRR4ESCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQ5usJE9IexG2k8ixvMOevHOM_kN3Vtg',
    appId: '1:767226093877:android:f8eaa5be21de9960cb6c7c',
    messagingSenderId: '767226093877',
    projectId: 'stunio-clone',
    databaseURL: 'https://stunio-clone-default-rtdb.firebaseio.com',
    storageBucket: 'stunio-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDny8eXXMcx2ptZ7o762zFTwl72s17NWqs',
    appId: '1:767226093877:ios:2fd7c55e6903117acb6c7c',
    messagingSenderId: '767226093877',
    projectId: 'stunio-clone',
    databaseURL: 'https://stunio-clone-default-rtdb.firebaseio.com',
    storageBucket: 'stunio-clone.appspot.com',
    iosClientId: '767226093877-v1ifhsrdcoksbshr1bh7lfj03ql6actf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDny8eXXMcx2ptZ7o762zFTwl72s17NWqs',
    appId: '1:767226093877:ios:2fd7c55e6903117acb6c7c',
    messagingSenderId: '767226093877',
    projectId: 'stunio-clone',
    databaseURL: 'https://stunio-clone-default-rtdb.firebaseio.com',
    storageBucket: 'stunio-clone.appspot.com',
    iosClientId: '767226093877-v1ifhsrdcoksbshr1bh7lfj03ql6actf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNoVAQ6l2TWGt4VQuE2sE8Ynk4KbdUKBM',
    appId: '1:767226093877:web:9084c80d3407a493cb6c7c',
    messagingSenderId: '767226093877',
    projectId: 'stunio-clone',
    authDomain: 'stunio-clone.firebaseapp.com',
    databaseURL: 'https://stunio-clone-default-rtdb.firebaseio.com',
    storageBucket: 'stunio-clone.appspot.com',
    measurementId: 'G-0RQ9B6Q5D2',
  );
}
